version: 0.2
#
# Build specifique pour le bot
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - $(aws ecr create-repository --region $AWS_DEFAULT_REGION --repository-name sydneygael/bot-demo | exit 0)
  build:
    commands:
      - echo Application build started on `date`
      - echo 'git sha $CODEBUILD_RESOLVED_SOURCE_VERSION'
      - export IMAGE_TAG=$(cat pom.xml | grep "^    <version>.*</version>$" | awk -F'[><]' '{print $3}')
      - echo Application build completed on `date`
      - echo Docker images build started on `date`
      - docker build -t sydneygael/bot-demo -f webhook/Dockerfile .
      - docker tag sydneygael/bot-demo:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/sydneygael/bot-demo:latest
  post_build:
    commands:
      - echo Docker images build completed on `date`
      - echo Pushing the docker images...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/sydneygael/bot-demo:latest
      - echo Docker images pushed on `date`
      - echo Copy du Dockerrun adhoc
      - cp aws/buildspec.yml .
      - cp aws/Dockerrun.aws.json Dockerrun.aws.json
artifacts:
  files:
    - buildspec.yml
    - Dockerrun.aws.json
